-- BizRethink Phase B (overlay 010 prerequisite): per-org SMTP credentials.
--
-- Mirrors the BizrethinkOrganisationSmtpConfig model in
-- packages/bizrethink/prisma-extensions/additions.prisma. Hand-written
-- (not generated by `prisma migrate dev`) because the additive-fork
-- discipline keeps the model in additions.prisma rather than
-- packages/prisma/schema.prisma at commit time. Verified against the
-- merged schema with `node packages/bizrethink/prisma-extensions/merge-into-schema.mjs`.

-- CreateTable
CREATE TABLE "BizrethinkOrganisationSmtpConfig" (
    "id" TEXT NOT NULL,
    "organisationId" TEXT NOT NULL,
    "transport" TEXT NOT NULL DEFAULT 'smtp-auth',
    "host" TEXT NOT NULL,
    "port" INTEGER NOT NULL DEFAULT 587,
    "secure" BOOLEAN NOT NULL DEFAULT false,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "fromName" TEXT NOT NULL,
    "fromAddress" TEXT NOT NULL,
    "lastTestedAt" TIMESTAMP(3),
    "lastTestError" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BizrethinkOrganisationSmtpConfig_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "BizrethinkOrganisationSmtpConfig_organisationId_key" ON "BizrethinkOrganisationSmtpConfig"("organisationId");
